version: '3.9'

services:
  kafka-00:
    image: bitnami/kafka:3.4
    container_name: kafka-00
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-00:9093,1@kafka-01:9093,2@kafka-02:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-00:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_00_data:/bitnami/kafka
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 30s
      retries: 5

  kafka-01:
    image: bitnami/kafka:3.4
    container_name: kafka-01
    ports:
      - "9095:9095"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-00:9093,1@kafka-01:9093,2@kafka-02:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-01:9092,EXTERNAL://localhost:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_01_data:/bitnami/kafka
    networks:
      - kafka-network

  kafka-02:
    image: bitnami/kafka:3.4
    container_name: kafka-02
    ports:
      - "9096:9096"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-00:9093,1@kafka-01:9093,2@kafka-02:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-02:9092,EXTERNAL://localhost:9096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_02_data:/bitnami/kafka
    networks:
      - kafka-network

  ui:
    image: provectuslabs/kafka-ui:v0.7.0
    container_name: kafka-ui-00
    ports:
      - "127.0.0.1:8085:8080"
      #- "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka-00:9092
      - KAFKA_CLUSTERS_0_NAME=kraft 
      - KAFKA_CLUSTERS_0_KSQLDBSERVER=http://ksqldb-server-00:8088
    networks:
      - kafka-network

  ksqldb-server-00:
    image: confluentinc/ksqldb-server:latest
    container_name: ksqldb-server-00
    depends_on:
     - kafka-00
     - kafka-01
     - kafka-02
    environment:
      KSQL_BOOTSTRAP_SERVERS: kafka-00:9092
    ports:
      - "8088:8088"
    networks:
      - kafka-network 

  ksqldb-cli-00:
    image: confluentinc/ksqldb-cli:latest
    container_name: ksqldb-cli-00
    depends_on:
      - ksqldb-server-00
    entrypoint: /bin/sh -c 'exec ksql http://ksqldb-server-00:8088'
    stdin_open: true
    tty: true
    networks:
      - kafka-network

  faust-app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: faust-app
    depends_on:
      - kafka-00
    networks:
      - kafka-network
    volumes:
      - ./app/blocked_users.csv:/app/blocked_users.csv
      - ./app/censored_words.csv:/app/censored_words.csv


volumes:
  kafka_00_data:
  kafka_01_data:
  kafka_02_data:

networks:
  kafka-network:
